apiVersion: apps/v1
kind: Deployment
metadata:
  name: elemana-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elemana-admin
  template:
    spec:
      containers:
        - name: elemana-admin
          image: ghcr.io/mohamedsalem66/elemana-admin:0.2-SNAPSHOT
